<?php if( !defined( '_VALID_MOS' ) && !defined( '_JEXEC' ) ) die( 'Direct Access to '.basename(__FILE__).' is not allowed.' );
/*
*
* @copyright Copyright (C) 2007 - 2010 RuposTel - All rights reserved.
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
* One Page checkout is free software released under GNU/GPL and uses code from VirtueMart
* VirtueMart is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
* 
*/



global $Itemid; 


global $jmshortcode;
if (!empty($jmshortcode) && (is_object($jmshortcode)))
$lang = $jmshortcode->shortcode;

echo $intro_article; 

/*
 Anything before and after this template is generated by a template file /pages/shop.cart.tpl.php of your VM template
 There you can change page title from Cart to Checkout and erase any text and button that are genereated under the checkout page 
*/

//echo $op_coupon; // will show coupon if enabled from common/couponField.tpl.php with corrected width to size
echo $html_in_between; // from configuration file.. if you don't want it, just comment it or put any html here to explain how should a customer use your cart, update quantity and so on
echo $google_checkout_button; // will load google checkout button if you have powersellersunite.com/googlecheckout installed


if (!empty($checkoutAdvertises)) {

?>
<div id="checkout-advertise-box">
		<?php
		if (!empty($checkoutAdvertises)) {
			foreach ($checkoutAdvertises as $checkoutAdvertise) {
				?>
				<div class="checkout-advertise">
					<?php echo $checkoutAdvertise; ?>
				</div>
				<?php
			}
		}
		?>
	</div>
<?php 
}

if (!empty($paypal_express_button)) { ?>
<div id="op_paypal_express" style="float: right; clear: both; width: 100%; padding-top: 10px;">
 <?php echo $paypal_express_button; ?>
</div>
<?php }

 ?>

<!-- start main onepage div, if javascript fails it will remain hidden -->
<div <?php if (empty($no_jscheck) || (!defined("_MIN_POV_REACHED"))) echo 'style="display: none;"'; ?> id="onepage_main_div">
<?php if (empty($no_continue_link) && (!empty($continue_link)) && ($continue_link != '//')) {  ?>
<div id="continue_button"  >
	<input type="button" class="bandBoxStyle" onclick="location.href='<?php echo $continue_link; ?>';" value="<?php echo OPCLang::_('COM_VIRTUEMART_CONTINUE_SHOPPING'); ?>" />
 </div>
<?php } ?>
<!-- start of checkout form -->
<form action="<?php echo $action_url; ?>" method="post" name="adminForm" class="form-va2lidate" autocomplete="off">
<!-- user info details -->

<!-- user registration and fields -->

<div id="billTo_box">
	<div id="billTo_head" class="bandBoxStyle"><?php echo OPCLang::_('COM_VIRTUEMART_USER_FORM_BILLTO_LBL'); ?></div>
	<div id="billTo_container"><?php echo $op_userfields; ?></div>
</div>


<!-- end of user info details -->
<!-- ship to address details -->
<?php if ($no_shipto != '1') { ?>
<div id="shipTo_box">
	<div id="shipTo_head" class="bandBoxStyle"><?php echo OPCLang::_('COM_VIRTUEMART_USER_FORM_SHIPTO_LBL'); ?></div>
	<div id="shipTo_container">
	<div id="onepage_useraddresses">
		<?php echo $op_shipto; // user data and his shipping addresse, they are fetched from checkout/get_shipping_address.tpl.php ?>
	</div>
	</div>
</div>


<?php } ?>


<!-- end ship to address details -->

<!-- shipping methodd -->
<div id="shipping_box" <?php if ($no_shipping || ($shipping_inside_basket)) echo ' style="display: none;" '; ?>>
	<div id="shipping_head" class="bandBoxStyle"><?php echo OPCLang::_('COM_VIRTUEMART_ORDER_PRINT_SHIPPING_LBL'); ?></div>
	<div id="shipping_container">	
		<!-- shipping methodd -->
		<div id="ajaxshipping" style="width: 90%;">
		<?php echo $shipping_method_html; // this prints all your shipping methods from checkout/list_shipping_methods.tpl.php ?>
		</div>
		
		<!-- end shipping methodd -->
	</div>
</div>
<?php
if (!empty($delivery_date)) { 
echo $delivery_date; 
 ?>

<?php } ?>	

<!-- end shipping methodd -->
<?php if (!empty($op_payment))
{

?>
<div id="payment_top_wrapper" <?php
if (!empty($force_hide_payment)) {
 echo ' style="display: none;" '; 
 
 }
 ?> >

<div id="payment_box">
	<div id="payment_head" class="bandBoxStyle"><?php echo OPCLang::_('COM_VIRTUEMART_CART_PAYMENT'); ?></div>
	<div id="payment_container">
	<!-- payment method -->

	<?php echo $op_payment; ?>
	
	<!-- end shipping methodd -->
	</div>

</div>
</div>
<?php 


}
?>


<?php
if (!empty($checkbox_products)) {
	?><div class="op_inside checkbox_wrapper bandbox_wrapper"  >
	<div id="payment_head" class="bandBoxStyle bandBoxStyleHeader"><?php echo OPCLang::_('COM_ONEPAGE_CHECKBOX_SECTION'); ?></div>
	<div id="payment_container"><?php echo $checkbox_products; ?></div>
	</div>
	<?php
}
?>
<!-- end payment method -->


<?php
if (false)	
if(VmConfig::get('oncheckout_show_legal_info',1) && (!empty($cart->vendor->vendor_terms_of_service)))
{
?>

				                                                   	
<!-- remove this section if you have 'must agree to tos' disabled' -->


<!-- show full TOS -->
	
<!-- end of full tos -->

<?php 

{
?>
<div id="cartTos_box">
	<div id="cartTos_head" class="bandBoxStyle"><?php echo OPCLang::_('COM_VIRTUEMART_CART_TOS'); ?></div>
	<div id="cartTos_container"><?php 
	echo $cart->vendor->vendor_terms_of_service; 
?>
	</div>
</div>

<?php 
}
}
?>
<br style="clear:both;">
<?php
	
if($show_full_tos)
{
?>

				                                                   	
<!-- remove this section if you have 'must agree to tos' disabled' -->


<!-- show full TOS -->
	
<!-- end of full tos -->

<?php 

{
?>
<div id="fullTos_box">
	<div id="fullTos_head" class="bandBoxStyle"><?php echo OPCLang::_('COM_VIRTUEMART_CART_TOS'); ?></div>
	<div id="fullTos_container">
	<?php 
	echo $tos_con;
	?>
	</div>
</div>
	
<?php 
}
}


?>
<div id="comment_box" <?php if (!$show_full_tos) echo ' style="width: 100%;" '; ?>>
	<div id="comment_head" class="bandBoxStyle"><?php 
		$comment = OPCLang::_('COM_VIRTUEMART_COMMENT_CART'); 
		if ($comment == 'COM_VIRTUEMART_COMMENT_CART')
		echo OPCLang::_('COM_VIRTUEMART_COMMENT');  
		else echo $comment; 
		?>
	</div>
	<div id="comment_container">
			<span id="customer_note_input" class="formField" <?php if (!$show_full_tos) echo ' style="width: 52%;" '; ?>>
								<label for="customer_note_box"><?php 
									$comment = OPCLang::_('COM_VIRTUEMART_COMMENT_CART'); 
								    if ($comment == 'COM_VIRTUEMART_COMMENT_CART')
									echo OPCLang::_('COM_VIRTUEMART_COMMENT');  
									else echo $comment; 

								?>:</label>
							   <textarea rows="3" cols="30" name="customer_comment" id="customer_note_box" ></textarea>
							   </span>
							   
							   <div id="payment_info" style="padding-top: 20px;clear:both"></div>
							 
							 
                        	
                        	 <div id="rbsubmit" >
                        	   <!-- show total amount at the bottom of checkout and payment information, don't change ids as javascript will not find them and OPC will not function -->
<div id="onepage_info_above_button">
<div style="display:none;">
<div id="onepage_total_inc_sh">
<?php
/*
 content of next divs will be changed by javascript, please don't change it's id, you may freely format it and if you add any content of txt fields it will not be overwritten by javascript 
*/
?>
<div id="totalam">
<div id="tt_order_subtotal_div"><span id="tt_order_subtotal_txt" class="bottom_totals_txt"></span><span id="tt_order_subtotal" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_order_payment_discount_before_div"><span id="tt_order_payment_discount_before_txt" class="bottom_totals_txt"></span><span class="bottom_totals" id="tt_order_payment_discount_before"></span><br class="op_clear"/></div>
<div id="tt_order_discount_before_div"><span id="tt_order_discount_before_txt" class="bottom_totals_txt"></span><span id="tt_order_discount_before" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_shipping_rate_div"><span id="tt_shipping_rate_txt" class="bottom_totals_txt"></span><span id="tt_shipping_rate" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_shipping_tax_div"><span id="tt_shipping_tax_txt" class="bottom_totals_txt"></span><span id="tt_shipping_tax" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_0_div"><span id="tt_tax_total_0_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_0" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_1_div"><span id="tt_tax_total_1_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_1" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_2_div"><span id="tt_tax_total_2_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_2" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_3_div"><span id="tt_tax_total_3_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_3" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_4_div"><span id="tt_tax_total_4_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_4" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_order_payment_discount_after_div"><span id="tt_order_payment_discount_after_txt" class="bottom_totals_txt"></span><span id="tt_order_payment_discount_after" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_order_discount_after_div"><span id="tt_order_discount_after_txt" class="bottom_totals_txt"></span><span id="tt_order_discount_after" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_total_div"><span id="tt_total_txt" class="bottom_totals_txt"></span><span id="tt_total" class="bottom_totals"></span><br class="op_clear"/></div>
</div>
<?php 
/*
* END of order total at the bottom
*/
?>
</div>
</div>
 <div><br /></div>
<!-- content of next div will be changed by javascript, please don't change it's id -->
 
<!-- end of total amount and payment info -->
<!-- submit button -->
</div>
</div> 

</div>

	
</div>
<!-- show TOS and checkbox before button -->
<?php

if ($tos_required)
{

?>
<div id="comment_box" <?php if (!$show_full_tos) echo ' style="width: 100%;" '; ?> >
	<div id="comment_head" class="bandBoxStyle"><?php 
	echo OPCLang::_('COM_VIRTUEMART_I_AGREE_TO_TOS'); 
	?></div>
	<div id="comment_container">


	<div id="agreed_div" class="formLabel " >
	


					<label for="agreed_field">
					<input value="1" type="checkbox" id="agreed_field" name="tosAccepted" <?php if (!empty($agree_checked)) echo ' checked="checked" '; ?> class="terms-of-service"  required="required" autocomplete="off" />
					<?php echo OPCLang::_('COM_VIRTUEMART_I_AGREE_TO_TOS'); 
					if (!empty($tos_link))
					{
					JHTMLOPC::_('behavior.modal', 'a.opcmodal'); 
					
					?><br /><a target="_blank" rel="{handler: 'iframe', size: {x: 500, y: 400}}" class="opcmodal" href="<?php echo $tos_link; ?>" onclick="javascript: return op_openlink(this); " >(<?php echo OPCLang::_('COM_VIRTUEMART_CART_TOS').' *'; ?>)</a><?php } ?></label>
				
		
	<?php 
	
echo $italian_checkbox;  
?>
	
	</div>
	
</div>
</div>

<?php
}
?>
<!-- end show TOS and checkbox before button -->

<?php
echo $op_basket; // will show either basket/basket_b2c.html.php or basket/basket_b2b.html 

?>
<!-- end show TOS and checkbox before button -->

<div id="rbsubmit2">

<div id="continue_button" style="float: left; clear: left; width: 40%;" >




<?php if (empty($no_continue_link) && (!empty($continue_link)) && ($continue_link != '//')) {  ?>

	<input type="button" class="bandBoxStyle bottomcontinue" onclick="location.href='<?php echo $continue_link; ?>';" value="<?php echo OPCLang::_('COM_VIRTUEMART_CONTINUE_SHOPPING'); ?>" />
<?php 
} 

?>

	</div>

 <div id="confirm_button_div" <?php if (empty($uid) && (!empty($use_multi_step) ) && (!empty($registration_html))) echo ' style="display: none;" ';?> >
	<input id="confirmbtn_button" type="submit" class="submitbtn bandBoxRedStyle" autocomplete="off" <?php echo $op_onclick ?>  value="<?php echo OPCLang::_('COM_VIRTUEMART_ORDER_CONFIRM_MNU') ?>" />
 </div>
</div>
<br style="clear: both;"/>

<?php echo $captcha; ?>
<!-- end of submit button -->




                        	 
                        	
                        	
                        	
	




<!-- customer note box -->

<!-- end of customer note -->

</form>

<!-- end of submit button -->
<!-- end of checkout form -->
<!-- end of main onepage div, if javascript fails it will remain hidden -->
</div>
<div id="tracking_div"></div>


<br style="clear: both; float: none;" />
<br style="clear: both; float: left;" />